In [1]:
import pandas as pd
import numpy as np

jahr = '2025'

#if jahr == '2025':
ghp="Daten entsoe/Gro_handelspreise_202311010000_202601010000_Viertelstunde.csv"
psf="Daten entsoe/Physikalischer_Stromfluss_202311010000_202601010000_Viertelstunde.csv"
kma="Daten entsoe/Kommerzieller_Au_enhandel_202311010000_202601010000_Viertelstunde.csv"
rez='Daten entsoe/Realisierte_Erzeugung_202311010000_202601010000_Viertelstunde.csv'
#else:
#    ghp="Daten entsoe/Gro_handelspreise_202311010000_202601020000_Stunde_Viertelstunde.csv"
#    psf="Daten entsoe/Physikalischer_Stromfluss_202311010000_202601020000_Viertelstunde.csv"
#    rez='Daten entsoe/Realisierte_Erzeugung_202311010000_202601020000_Viertelstunde.csv'

Strompreis=pd.read_csv(ghp,na_values='-',header=0 ,sep=';', decimal=",", thousands=".")

In [2]:
Strompreis['Datum']=pd.to_datetime(Strompreis['Datum von'],format='%d.%m.%Y %H:%M')
Strompreis=Strompreis.sort_values('Datum',kind='stable')
Strompreis=Strompreis[Strompreis['Datum von'].str[14:16]=='00']
Strompreis['Datum']=pd.to_datetime(Strompreis['Datum von'],format='%d.%m.%Y %H:%M')
Strompreis['Datum']=Strompreis['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Strompreis['Date']=Strompreis['Datum'].dt.tz_convert('UTC')
Strompreis=Strompreis.set_index('Date')

In [3]:
datei=kma
dtype={'Datum von':"string",'Datum bis':"string"
       ,'Nettoexport [MWh] Originalauflösungen':np.float64
       ,'Niederlande (Export) [MWh] Originalauflösungen':np.float64
       ,'Niederlande (Import) [MWh] Originalauflösungen':np.float64
       ,'Schweiz (Export) [MWh] Originalauflösungen':np.float64
       ,'Schweiz (Import) [MWh] Originalauflösungen':np.float64
       ,'Dänemark (Export) [MWh] Originalauflösungen':np.float64
       ,'Dänemark (Import) [MWh] Originalauflösungen':np.float64
       ,'Tschechien (Export) [MWh] Originalauflösungen':np.float64
       ,'Tschechien (Import) [MWh] Originalauflösungen':np.float64
       ,'Luxemburg (Export) [MWh] Originalauflösungen':np.float64
       ,'Luxemburg (Import) [MWh] Originalauflösungen':np.float64
       ,'Schweden (Export) [MWh] Originalauflösungen':np.float64
       ,'Schweden (Import) [MWh] Originalauflösungen':np.float64
       ,'Österreich (Export) [MWh] Originalauflösungen':np.float64
       ,'Österreich (Import) [MWh] Originalauflösungen':np.float64
       ,'Frankreich (Export) [MWh] Originalauflösungen':np.float64
       ,'Frankreich (Import) [MWh] Originalauflösungen':np.float64
       ,'Polen (Export) [MWh] Originalauflösungen':np.float64
       ,'Polen (Import) [MWh] Originalauflösungen':np.float64
       ,'Norwegen (Export) [MWh] Originalauflösungen':np.float64
       ,'Norwegen (Import) [MWh] Originalauflösungen':np.float64
       ,'Belgien (Export) [MWh] Originalauflösungen':np.float64
       ,'Belgien (Import) [MWh] Originalauflösungen':np.float64}


#Stromfluss=pd.read_csv("Daten entsoe/Physikalischer_Stromfluss_202311010000_202502010000_Viertelstunde.csv",sep=';', decimal=",", thousands=".",dtype=dtype,on_bad_lines='skip')
Stromfluss=pd.read_csv(datei,sep=';', decimal=",", thousands=".",header=0,na_values='-',on_bad_lines='skip')

In [4]:
Stromfluss['Datum']=pd.to_datetime(Stromfluss['Datum von'],format='%d.%m.%Y %H:%M')
#Stromfluss=Stromfluss.sort_values('Datum',kind='stable')
Stromfluss['Datum']=pd.to_datetime(Stromfluss['Datum von'],format='%d.%m.%Y %H:%M')
Stromfluss['Datum']=Stromfluss['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Stromfluss['Date']=Stromfluss['Datum'].dt.tz_convert('UTC')
Stromfluss=Stromfluss[Stromfluss['Date'].dt.year==int(jahr)]
Stromfluss=Stromfluss.set_index('Date').fillna(0)
pm_cat=Stromfluss['Nettoexport [MWh] Originalauflösungen']
Stromfluss['+-']=(np.where(pm_cat<0,'0: Import','1: Export'))
Strompreis=Strompreis.reindex(Stromfluss.index).ffill()
#Stromfluss.rename(columns={'Nettoexport [MWh] Originalauflösungen':'Nettoexport [TWh]'})
Stromfluss['Preis']=Strompreis['Deutschland/Luxemburg [€/MWh] Originalauflösungen']
Stromfluss['Nettoexport [TWh]']=Stromfluss['Nettoexport [MWh] Originalauflösungen']/1000000
Stromfluss['Wert Mio €']=Stromfluss['Preis']*Stromfluss['Nettoexport [MWh] Originalauflösungen']/1000000
#Stromfluss=Stromfluss.set_index('Date')

In [5]:
# funktioniert: 
#Stromfluss.groupby([Stromfluss.index.month,Stromfluss['+-']])[['Nettoexport [TWh]','Wert Mio €']].agg(['sum'])
df=Stromfluss.reset_index()
df['Monat']=df['Date'].dt.month
df['Jahr']=df['Date'].dt.year
Strom=pd.pivot_table(df,index='Monat', columns=['+-'],values=['Wert Mio €','Nettoexport [TWh]'], aggfunc='sum',margins=True,margins_name=jahr)

In [6]:
#Strom['Durchschnittspreis [€/MWh]','0: Import']=Strom['Wert Mio €']['0: Import']/Strom['Nettoexport [TWh]']['0: Import']
#Strom['Durchschnittspreis [€/MWh]','1: Export']=Strom['Wert Mio €']['1: Export']/Strom['Nettoexport [TWh]']['1: Export']
Strom=Strom.join(Strom[['Wert Mio €']].div(Strom['Nettoexport [TWh]']).rename(columns={'Wert Mio €':'Durchschnittspreis [€/MWh]'}))
Strom=Strom.drop(columns=('Durchschnittspreis [€/MWh]',jahr), axis=1)

In [7]:
Strom

      Nettoexport [TWh]                         Wert Mio €              \
+-            0: Import  1: Export       2025    0: Import   1: Export
Monat
1             -2.305606   1.425513  -0.880092  -371.918728   81.097112
2             -2.605407   0.766618  -1.838789  -391.742087   81.726312
3             -3.068767   0.766561  -2.302207  -379.194466   19.564696
4             -3.561295   0.728892  -2.832402  -371.283171   -1.028349
5             -3.137686   1.019658  -2.118028  -323.758667  -13.474645
6             -2.940741   1.552336  -1.388405  -299.427269   -3.091917
7             -3.857641   0.501044  -3.356597  -404.339254   10.749475
8             -4.370708   0.767860  -3.602848  -451.179907    4.723468
9             -3.088673   0.941754  -2.146919  -369.204558    7.803961
10            -2.245324   1.824230  -0.421094  -288.499606   50.713001
11            -0.459026   0.015926  -0.443101   -41.343879    0.728197
12                  NaN   0.000000   0.000000          NaN    0.000000
2025         -31.640874  10.310392 -21.330482 -3691.891592  239.511312

                   Durchschnittspreis [€/MWh]
+-            2025                  0: Import   1: Export
Monat
1      -290.821616                 161.310631   56.889756
2      -310.015775                 150.357347  106.606270
3      -359.629770                 123.565720   25.522696
4      -372.311520                 104.255112   -1.410837
5      -337.233312                 103.183899  -13.214869
6      -302.519185                 101.820342   -1.991783
7      -393.589780                 104.815149   21.454143
8      -446.456439                 103.228108    6.151469
9      -361.400597                 119.535010    8.286625
10     -237.786605                 128.489104   27.799681
11      -40.615681                  90.068622   45.724647
12        0.000000                        NaN         NaN
2025  -3452.380279                 116.681087   23.230087

In [8]:
datei=rez
Stromerzeugung=pd.read_csv(datei,sep=';', decimal=",", thousands=".",header=0,na_values='-',on_bad_lines='skip')

In [9]:
Stromerzeugung['Datum']=pd.to_datetime(Stromerzeugung['Datum von'],format='%d.%m.%Y %H:%M')
Stromerzeugung['Datum']=Stromerzeugung['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Stromerzeugung['Date']=Stromerzeugung['Datum'].dt.tz_convert('UTC')
Stromerzeugung=Stromerzeugung[Stromerzeugung['Date'].dt.year==int(jahr)]
Stromerzeugung=Stromerzeugung.set_index('Date').fillna(0)

In [10]:
replace={ 
'Biomasse [MWh] Originalauflösungen':'Biomasse'
,'Wasserkraft [MWh] Originalauflösungen':'Wasserkraft'
,'Wind Offshore [MWh] Originalauflösungen':'Wind off'
,'Wind Onshore [MWh] Originalauflösungen':'Wind on'
,'Photovoltaik [MWh] Originalauflösungen':'Photovoltaik'
,'Sonstige Erneuerbare [MWh] Originalauflösungen':'Sonstige Erneuerbare'
,'Kernenergie [MWh] Originalauflösungen':'Kernenergie'
,'Braunkohle [MWh] Originalauflösungen':'Braunkohle'
,'Steinkohle [MWh] Originalauflösungen':'Steinkohle'
,'Erdgas [MWh] Originalauflösungen':'Erdgas'
,'Pumpspeicher [MWh] Originalauflösungen':'Pumpspeicher'
,'Sonstige Konventionelle [MWh] Originalauflösungen':'Sonstige Konventionelle'}
Stromerzeugung=Stromerzeugung.rename(columns=replace)
Stromerzeugung['Preis']=Strompreis['Deutschland/Luxemburg [€/MWh] Originalauflösungen']

In [11]:
piv=[]
for cur in replace:
    sm=replace[cur]
    Stromerzeugung[sm+' Wert Mio €']=Stromerzeugung['Preis']*Stromerzeugung[sm]/1000000
    Stromerzeugung[sm]=Stromerzeugung[sm]/1000000
    piv=piv+[sm,sm+' Wert Mio €']
Stromerzeugung['+-']=(np.where(Stromerzeugung['Preis']<0,'0: neg','1: pos'))

In [12]:
df=Stromerzeugung.reset_index()
df['Monat']=df['Date'].dt.month
df['Jahr']=df['Date'].dt.year
#df=df.drop(columns=['Date','Datum von','Datum bis','Jahr','Datum','Preis'], axis=1)
df_mon=df.groupby(['Monat','+-']).sum(numeric_only=True)
df_jahr  =df.groupby(['Jahr','+-']).sum(numeric_only=True).rename_axis(index={'Jahr':'Monat'})

df_mon=df_mon.drop(columns=('Jahr'), axis=1)
df_jahr=df_jahr.drop(columns=('Monat'), axis=1)

df_erg=pd.concat([df_mon,df_jahr])

for cur in replace:
    sm=replace[cur]
    df_erg[sm+' €/MWh']=df_erg[sm+' Wert Mio €']/df_erg[sm]


#Strom_ez=pd.pivot_table(df,index='Monat', columns=['+-'],values=piv, aggfunc='sum',margins=True,margins_name=jahr)
#Strom_ez=Strom_ez.join(Strom[['Wert Mio €']].div(Strom['Nettoexport [TWh]']).rename(columns={'Wert Mio €':'Durchschnittspreis [€/MWh]'}))
#Strom_ez=Strom_ez.drop(columns=('Durchschnittspreis [€/MWh]',jahr), axis=1)

In [13]:
df_erg.to_csv('test.csv')

In [14]:
df_erg

               Biomasse  Wasserkraft   Wind off    Wind on  Photovoltaik  \
Monat +-
1     0: neg   0.053374     0.019950   0.032634   0.510138      0.056735
      1: pos   3.189983     1.285757   2.505589  12.717119      1.576653
2     1: pos   2.993729     1.101339   2.259758   7.258485      3.033001
3     0: neg   0.114252     0.041557   0.052139   0.443366      0.930577
      1: pos   3.045524     0.932265   1.838048   6.092140      6.021991
4     0: neg   0.280091     0.101989   0.068532   0.473704      2.934880
      1: pos   2.711320     0.905872   1.011444   5.398544      6.066265
5     0: neg   0.453371     0.187264   0.217463   1.257315      4.486026
      1: pos   2.488112     0.992348   1.645148   6.646398      5.790053
6     0: neg   0.492668     0.235905   0.197908   1.797527      4.976705
      1: pos   2.342897     1.110044   1.653901   6.912052      5.624105
7     0: neg   0.040762     0.018317   0.028625   0.120068      0.471732
      1: pos   2.852935     1.389855   1.530292   6.066310      8.645852
8     0: neg   0.241949     0.122422   0.141768   0.553057      2.205290
      1: pos   2.579911     1.432437   1.560511   4.920989      7.795529
9     0: neg   0.224515     0.095569   0.203552   1.259631      1.653217
      1: pos   2.547073     1.164943   2.198962   8.443734      5.089568
10    0: neg   0.206000     0.072953   0.226241   1.833405      0.353874
      1: pos   2.821852     1.032728   2.674569  11.940733      3.502760
11    1: pos   0.558926     0.201550   0.586761   2.273321      0.593371
12    1: pos   0.000000     0.000000   0.000000   0.000000      0.000000
2025  0: neg   2.106981     0.895926   1.168863   8.248212     18.069037
      1: pos  28.132260    11.549138  19.464983  78.669825     53.739148

              Sonstige Erneuerbare  Kernenergie  Braunkohle  Steinkohle  \
Monat +-
1     0: neg              0.001765          0.0    0.045756    0.028566
      1: pos              0.094445          0.0    6.789585    3.586727
2     1: pos              0.084722          0.0    7.092657    4.235787
3     0: neg              0.003556          0.0    0.144085    0.055064
      1: pos              0.084215          0.0    7.144591    3.134103
4     0: neg              0.008209          0.0    0.282830    0.076843
      1: pos              0.072761          0.0    5.054667    2.314073
5     0: neg              0.012636          0.0    0.394503    0.088100
      1: pos              0.063120          0.0    3.702067    0.894679
6     0: neg              0.012251          0.0    0.394282    0.110179
      1: pos              0.053285          0.0    3.247742    1.099093
7     0: neg              0.001036          0.0    0.044955    0.008229
      1: pos              0.065545          0.0    5.706925    1.895981
8     0: neg              0.006587          0.0    0.195284    0.022005
      1: pos              0.069500          0.0    4.322432    1.278917
9     0: neg              0.005750          0.0    0.176751    0.042972
      1: pos              0.060642          0.0    4.757188    1.360146
10    0: neg              0.003103          0.0    0.115644    0.033467
      1: pos              0.060346          0.0    5.514976    2.124968
11    1: pos              0.011769          0.0    0.905177    0.294095
12    1: pos              0.000000          0.0    0.000000    0.000000
2025  0: neg              0.054893          0.0    1.794089    0.465424
      1: pos              0.720350          0.0   54.238006   22.218569

                 Erdgas  ...  Wind off €/MWh  Wind on €/MWh  \
Monat +-                 ...
1     0: neg   0.056281  ...       -0.138830      -0.113956
      1: pos   7.880320  ...      105.383099      90.771734
2     1: pos   7.711784  ...      118.766248     116.171642
3     0: neg   0.091684  ...       -4.812619      -7.807956
      1: pos   5.569776  ...       91.143175      86.561313
4     0: neg   0.159998  ...      -10.536542     -12.212634
      1: pos   3.531320  ...       84.758109      85.449788
5     0: neg   0.253323  ...       -4.772882      -6.117728
      1: pos   2.879609  ...       81.376558      79.107311
6     0: neg   0.249313  ...       -7.094573     -10.504724
      1: pos   2.155772  ...       78.205108      74.546499
7     0: neg   0.019280  ...       -1.197444      -1.396316
      1: pos   2.900775  ...       87.311863      84.628737
8     0: neg   0.110019  ...       -3.482395      -5.072664
      1: pos   2.909858  ...       78.494410      79.122099
9     0: neg   0.117592  ...       -4.410705      -4.921652
      1: pos   3.686720  ...       80.789940      76.484376
10    0: neg   0.105863  ...       -0.966371      -1.098705
      1: pos   5.157870  ...       80.740928      68.668368
11    1: pos   0.745870  ...       77.126810      75.020121
12    1: pos   0.000000  ...             NaN            NaN
2025  0: neg   1.163352  ...       -4.332378      -5.706267
      1: pos  45.129674  ...       89.589779      83.466989

              Photovoltaik €/MWh  Sonstige Erneuerbare €/MWh  \
Monat +-
1     0: neg           -0.182518                   -0.108640
      1: pos          119.731569                  117.223672
2     1: pos          110.896202                  128.784187
3     0: neg           -4.388256                   -5.349125
      1: pos           59.354509                   98.619030
4     0: neg          -20.190133                  -20.260166
      1: pos           56.274278                   89.374794
5     0: neg          -20.295137                  -16.736602
      1: pos           54.173432                   85.227459
6     0: neg          -12.495948                  -11.484010
      1: pos           48.869298                   82.372002
7     0: neg           -1.029000                   -1.083074
      1: pos           63.142345                   89.070224
8     0: neg           -6.403958                   -6.022202
      1: pos           52.099382                   84.400174
9     0: neg           -7.922789                   -6.727830
      1: pos           61.295849                   91.859251
10    0: neg           -1.000987                   -1.246179
      1: pos           80.716572                   94.065201
11    1: pos           66.371394                   78.127163
12    1: pos                 NaN                         NaN
2025  0: neg          -13.539353                  -11.313772
      1: pos           63.242315                   97.771086

              Kernenergie €/MWh  Braunkohle €/MWh  Steinkohle €/MWh  \
Monat +-
1     0: neg                NaN         -0.110343         -0.102286
      1: pos                NaN        127.494047        129.252891
2     1: pos                NaN        131.746877        134.153463
3     0: neg                NaN         -4.453934         -4.852115
      1: pos                NaN        108.501428        112.511844
4     0: neg                NaN        -16.191732        -14.528324
      1: pos                NaN         96.520077        100.653787
5     0: neg                NaN        -14.310472        -14.398963
      1: pos                NaN         93.813120         97.154883
6     0: neg                NaN        -10.482209        -10.957739
      1: pos                NaN         93.362339        100.547646
7     0: neg                NaN         -1.079746         -1.051148
      1: pos                NaN         96.486905        100.771899
8     0: neg                NaN         -5.504254         -4.087327
      1: pos                NaN         94.077433        103.181221
9     0: neg                NaN         -6.482388         -4.468245
      1: pos                NaN        104.338758        111.406527
10    0: neg                NaN         -1.093552         -0.999702
      1: pos                NaN        106.150497        111.088407
11    1: pos                NaN         86.034981         89.291051
12    1: pos                NaN               NaN               NaN
2025  0: neg                NaN         -9.698756         -8.994845
      1: pos                NaN        107.500295        114.844850

              Erdgas €/MWh  Pumpspeicher €/MWh  Sonstige Konventionelle €/MWh
Monat +-
1     0: neg     -0.103112           -0.102187                      -0.109475
      1: pos    134.418009          161.487537                     118.255164
2     1: pos    137.673634          161.827126                     129.240023
3     0: neg     -4.642787           -5.086228                      -5.513300
      1: pos    113.877076          140.088326                     100.020535
4     0: neg    -18.282158          -22.048448                     -18.339787
      1: pos    101.345799          123.161660                      90.123352
5     0: neg    -14.939582          -16.470526                     -14.885317
      1: pos     97.252204          114.906522                      85.100219
6     0: neg    -11.061864           -7.734589                     -11.276221
      1: pos     97.003795          114.678908                      81.897427
7     0: neg     -1.095065           -1.371649                      -1.054166
      1: pos    101.480295          119.479717                      89.675235
8     0: neg     -5.410673           -2.598683                      -5.520348
      1: pos     99.901258          116.745537                      84.829847
9     0: neg     -5.857432           -5.904058                      -6.162235
      1: pos    110.581826          139.215858                      93.265800
10    0: neg     -1.080120           -0.762044                      -1.187195
      1: pos    111.060986          127.174447                      93.722244
11    1: pos     85.309905          104.775064                      78.586409
12    1: pos           NaN                 NaN                            NaN
2025  0: neg     -9.729221           -6.600180                     -10.100205
      1: pos    115.921718          130.808254                      97.228331

[23 rows x 37 columns]

In [52]:
Stromfluss.to_csv('test.csv')