In [35]:
import pandas as pd
import numpy as np

jahr = '2025'

if jahr == '2025':
    ghp="Daten entsoe/Gro_handelspreise_202501010000_202601010000_Stunde.csv"
    psf="Daten entsoe/Physikalischer_Stromfluss_202501010000_202601010000_Viertelstunde.csv"
    rez='Daten entsoe/Realisierte_Erzeugung_202501010000_202601010000_Viertelstunde.csv'
else:
    ghp="Daten entsoe/Gro_handelspreise_202311010000_202502010000_Stunde.csv"
    psf="Daten entsoe/Physikalischer_Stromfluss_202311010000_202502010000_Viertelstunde.csv"
    rez='Daten entsoe/Realisierte_Erzeugung_202311010000_202502010000_Viertelstunde.csv'

Strompreis=pd.read_csv(ghp,na_values='-',header=0 ,sep=';', decimal=",", thousands=".")

In [29]:
Strompreis['Datum']=pd.to_datetime(Strompreis['Datum von'],format='%d.%m.%Y %H:%M')
Strompreis=Strompreis.sort_values('Datum',kind='stable')
Strompreis['Datum']=pd.to_datetime(Strompreis['Datum von'],format='%d.%m.%Y %H:%M')
Strompreis['Datum']=Strompreis['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Strompreis['Date']=Strompreis['Datum'].dt.tz_convert('UTC')
Strompreis=Strompreis.set_index('Date')

In [30]:
datei=psf
dtype={'Datum von':"string",'Datum bis':"string"
       ,'Nettoexport [MWh] Originalauflösungen':np.float64
       ,'Niederlande (Export) [MWh] Originalauflösungen':np.float64
       ,'Niederlande (Import) [MWh] Originalauflösungen':np.float64
       ,'Schweiz (Export) [MWh] Originalauflösungen':np.float64
       ,'Schweiz (Import) [MWh] Originalauflösungen':np.float64
       ,'Dänemark (Export) [MWh] Originalauflösungen':np.float64
       ,'Dänemark (Import) [MWh] Originalauflösungen':np.float64
       ,'Tschechien (Export) [MWh] Originalauflösungen':np.float64
       ,'Tschechien (Import) [MWh] Originalauflösungen':np.float64
       ,'Luxemburg (Export) [MWh] Originalauflösungen':np.float64
       ,'Luxemburg (Import) [MWh] Originalauflösungen':np.float64
       ,'Schweden (Export) [MWh] Originalauflösungen':np.float64
       ,'Schweden (Import) [MWh] Originalauflösungen':np.float64
       ,'Österreich (Export) [MWh] Originalauflösungen':np.float64
       ,'Österreich (Import) [MWh] Originalauflösungen':np.float64
       ,'Frankreich (Export) [MWh] Originalauflösungen':np.float64
       ,'Frankreich (Import) [MWh] Originalauflösungen':np.float64
       ,'Polen (Export) [MWh] Originalauflösungen':np.float64
       ,'Polen (Import) [MWh] Originalauflösungen':np.float64
       ,'Norwegen (Export) [MWh] Originalauflösungen':np.float64
       ,'Norwegen (Import) [MWh] Originalauflösungen':np.float64
       ,'Belgien (Export) [MWh] Originalauflösungen':np.float64
       ,'Belgien (Import) [MWh] Originalauflösungen':np.float64}


#Stromfluss=pd.read_csv("Daten entsoe/Physikalischer_Stromfluss_202311010000_202502010000_Viertelstunde.csv",sep=';', decimal=",", thousands=".",dtype=dtype,on_bad_lines='skip')
Stromfluss=pd.read_csv(datei,sep=';', decimal=",", thousands=".",header=0,na_values='-',on_bad_lines='skip')

In [31]:
Stromfluss['Datum']=pd.to_datetime(Stromfluss['Datum von'],format='%d.%m.%Y %H:%M')
#Stromfluss=Stromfluss.sort_values('Datum',kind='stable')
Stromfluss['Datum']=pd.to_datetime(Stromfluss['Datum von'],format='%d.%m.%Y %H:%M')
Stromfluss['Datum']=Stromfluss['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Stromfluss['Date']=Stromfluss['Datum'].dt.tz_convert('UTC')
Stromfluss=Stromfluss[Stromfluss['Date'].dt.year==int(jahr)]
Stromfluss=Stromfluss.set_index('Date').fillna(0)
pm_cat=Stromfluss['Nettoexport [MWh] Originalauflösungen']
Stromfluss['+-']=(np.where(pm_cat<0,'0: Import','1: Export'))
Strompreis=Strompreis.reindex(Stromfluss.index).ffill()
#Stromfluss.rename(columns={'Nettoexport [MWh] Originalauflösungen':'Nettoexport [TWh]'})
Stromfluss['Preis']=Strompreis['Deutschland/Luxemburg [€/MWh] Originalauflösungen']
Stromfluss['Nettoexport [TWh]']=Stromfluss['Nettoexport [MWh] Originalauflösungen']/1000000
Stromfluss['Wert Mio €']=Stromfluss['Preis']*Stromfluss['Nettoexport [MWh] Originalauflösungen']/1000000
#Stromfluss=Stromfluss.set_index('Date')

In [32]:
# funktioniert: 
#Stromfluss.groupby([Stromfluss.index.month,Stromfluss['+-']])[['Nettoexport [TWh]','Wert Mio €']].agg(['sum'])
df=Stromfluss.reset_index()
df['Monat']=df['Date'].dt.month
df['Jahr']=df['Date'].dt.year
Strom=pd.pivot_table(df,index='Monat', columns=['+-'],values=['Wert Mio €','Nettoexport [TWh]'], aggfunc='sum',margins=True,margins_name=jahr)

In [33]:
#Strom['Durchschnittspreis [€/MWh]','0: Import']=Strom['Wert Mio €']['0: Import']/Strom['Nettoexport [TWh]']['0: Import']
#Strom['Durchschnittspreis [€/MWh]','1: Export']=Strom['Wert Mio €']['1: Export']/Strom['Nettoexport [TWh]']['1: Export']
Strom=Strom.join(Strom[['Wert Mio €']].div(Strom['Nettoexport [TWh]']).rename(columns={'Wert Mio €':'Durchschnittspreis [€/MWh]'}))
Strom=Strom.drop(columns=('Durchschnittspreis [€/MWh]',jahr), axis=1)

In [34]:
Strom

      Nettoexport [TWh]                      Wert Mio €              \
+-            0: Import 1: Export      2025   0: Import   1: Export
Monat
1             -2.245649  1.582476 -0.663172 -363.076495  101.585446
2             -0.913130  0.006413 -0.906717 -137.511381    0.722051
3                   NaN  0.000000  0.000000         NaN    0.000000
4                   NaN  0.000000  0.000000         NaN    0.000000
5                   NaN  0.000000  0.000000         NaN    0.000000
6                   NaN  0.000000  0.000000         NaN    0.000000
7                   NaN  0.000000  0.000000         NaN    0.000000
8                   NaN  0.000000  0.000000         NaN    0.000000
9                   NaN  0.000000  0.000000         NaN    0.000000
10                  NaN  0.000000  0.000000         NaN    0.000000
11                  NaN  0.000000  0.000000         NaN    0.000000
12                  NaN  0.000000  0.000000         NaN    0.000000
2025          -3.158778  1.588889 -1.569889 -500.587876  102.307497

                  Durchschnittspreis [€/MWh]
+-           2025                  0: Import   1: Export
Monat
1     -261.491049                 161.680020   64.193989
2     -136.789330                 150.593473  112.596139
3        0.000000                        NaN         NaN
4        0.000000                        NaN         NaN
5        0.000000                        NaN         NaN
6        0.000000                        NaN         NaN
7        0.000000                        NaN         NaN
8        0.000000                        NaN         NaN
9        0.000000                        NaN         NaN
10       0.000000                        NaN         NaN
11       0.000000                        NaN         NaN
12       0.000000                        NaN         NaN
2025  -398.280379                 158.475156   64.389339

In [36]:
datei=rez
Stromerzeugung=pd.read_csv(datei,sep=';', decimal=",", thousands=".",header=0,na_values='-',on_bad_lines='skip')

In [37]:
Stromerzeugung['Datum']=pd.to_datetime(Stromerzeugung['Datum von'],format='%d.%m.%Y %H:%M')
Stromerzeugung['Datum']=Stromerzeugung['Datum'].dt.tz_localize('Europe/Berlin',ambiguous='infer')
Stromerzeugung['Date']=Stromerzeugung['Datum'].dt.tz_convert('UTC')
Stromerzeugung=Stromerzeugung[Stromerzeugung['Date'].dt.year==int(jahr)]
Stromerzeugung=Stromerzeugung.set_index('Date').fillna(0)

In [38]:
Stromerzeugung=Stromerzeugung.rename(columns={'Wind Offshore [MWh] Originalauflösungen':'Wind Off','Wind Onshore [MWh] Originalauflösungen':'Wind On','Photovoltaik [MWh] Originalauflösungen':'PV'})

In [39]:
pv=Stromerzeugung['PV']/1000000
divi=3
x=sum(pv)
y=sum(np.where(pv>max(pv)/divi,max(pv)/divi,pv))
z=y/x
z,y,x

(0.72182365483227, 1.6129875000000178, 2.2346005)

In [59]:
sum(np.where(pv>max(pv)/2,max(pv)/2,pv))

54.70061799999507

In [55]:
max(Stromerzeugung['PV'])

11753.0

In [40]:
Stromerzeugung

,Datum von,Datum bis,Biomasse [MWh] Originalauflösungen,Wasserkraft [MWh] Originalauflösungen,Wind Off,Wind On,PV,Sonstige Erneuerbare [MWh] Originalauflösungen,Kernenergie [MWh] Originalauflösungen,Braunkohle [MWh] Originalauflösungen,Steinkohle [MWh] Originalauflösungen,Erdgas [MWh] Originalauflösungen,Pumpspeicher [MWh] Originalauflösungen,Sonstige Konventionelle [MWh] Originalauflösungen,Datum
Date,,,,,,,,,,,,,,,
2025-01-01 00:00:00+00:00,01.01.2025 01:00,01.01.2025 01:15,1009.25,302.50,562.75,8583.25,0.0,26.25,0.0,957.75,676.75,1126.75,91.75,329.25,2025-01-01 01:00:00+01:00
2025-01-01 00:15:00+00:00,01.01.2025 01:15,01.01.2025 01:30,996.50,293.75,627.00,8655.00,0.0,26.25,0.0,964.25,681.50,1058.25,21.25,327.50,2025-01-01 01:15:00+01:00
2025-01-01 00:30:00+00:00,01.01.2025 01:30,01.01.2025 01:45,998.00,301.25,602.00,8674.50,0.0,26.25,0.0,921.25,679.75,1053.00,31.25,329.50,2025-01-01 01:30:00+01:00
2025-01-01 00:45:00+00:00,01.01.2025 01:45,01.01.2025 02:00,996.75,302.50,601.00,8695.00,0.0,26.25,0.0,896.00,681.00,1090.00,0.00,329.25,2025-01-01 01:45:00+01:00
2025-01-01 01:00:00+00:00,01.01.2025 02:00,01.01.2025 02:15,995.25,298.25,668.75,8731.00,0.0,26.25,0.0,827.25,680.75,1046.75,1.00,328.25,2025-01-01 02:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-31 21:45:00+00:00,31.12.2025 22:45,31.12.2025 23:00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,2025-12-31 22:45:00+01:00
2025-12-31 22:00:00+00:00,31.12.2025 23:00,31.12.2025 23:15,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,2025-12-31 23:00:00+01:00
2025-12-31 22:15:00+00:00,31.12.2025 23:15,31.12.2025 23:30,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,2025-12-31 23:15:00+01:00
2025-12-31 22:30:00+00:00,31.12.2025 23:30,31.12.2025 23:45,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,2025-12-31 23:30:00+01:00
2025-12-31 22:45:00+00:00,31.12.2025 23:45,01.01.2026 00:00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,2025-12-31 23:45:00+01:00